import "../styles/globals.css"
import { MoralisProvider } from "react-moralis"
import Header from "../components/Header"
import Head from "next/head"

const NEXT_PUBLIC_MORALIS_APP_ID = process.env.NEXT_PUBLIC_MORALIS_APP_ID
const NEXT_PUBLIC_MORALIS_SERVER_URL =
  process.env.NEXT_PUBLIC_MORALIS_SERVER_URL

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>NextJs NFT Marketplace - Moralis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MoralisProvider
        appId={NEXT_PUBLIC_MORALIS_APP_ID}
        serverUrl={NEXT_PUBLIC_MORALIS_SERVER_URL}
      >
        <Header />
        <Component {...pageProps} />
      </MoralisProvider>
    </div>
  )
}

export default MyApp
